/*
 *  mosquitto_pub -v -h 192.168.2.222 -u dirk -P ****** -t "smarthome/infodisplay/message" -m "test"
 */
#define WEB_TITLE               "wifi display"
#define HOSTNAME 				"infodisplay"
#define MQTT_CLIENT_ID 			"infodisplay"
#define MQTT_SUBSCRIBE_TOPIC 	"smarthome/infodisplay/#"
#define MQTT_WILL_TOPIC 	    "smarthome/infodisplay/status"
#define MQTT_WILL_MESSAGE	    "infodisplay is offline"
#define MQTT_TOPIC_MESSAGE 		"smarthome/infodisplay/message"
#define MQTT_TOPIC_JSON 		"smarthome/infodisplay/json"
#define MQTT_TOPIC_NOTICE 		"smarthome/infodisplay/notice"
#define MQTT_TOPIC_ALARM 		"smarthome/infodisplay/alarm"
#define MQTT_TOPIC_DIM 			"smarthome/infodisplay/dim"
#define MQTT_TOPIC_SPEED 		"smarthome/infodisplay/speed"
#define MQTT_TOPIC_STATIC 		"smarthome/infodisplay/static"
#define MQTT_TOPIC_SCROLL 		"smarthome/infodisplay/scroll"
#define MQTT_TOPIC_WIFI 		"smarthome/infodisplay/wifi"
#define MQTT_TOPIC_RESET 		"smarthome/infodisplay/reset"
#define MQTT_TOPIC_ON 		    "smarthome/infodisplay/on"
#define MQTT_TOPIC_OFF 		    "smarthome/infodisplay/off"